name: Build and release the app

on:
  push:
    branches:
      - master

# Allow one concurrent build for each branch
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v3

      - name: Setup Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build for Win & Linux with electronuserland/builder:wine
        uses: addnab/docker-run-action@v3
        with:
          image: electronuserland/builder:wine
          options: -e GITHUB_TOKEN -v ${{ github.workspace }}:/project
          run: yarn && yarn build --win --linux --publish always
